

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_chat
    ports:
      - "5432:5432"
    
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  backend:
    build: ./server
    container_name: web_chat_backend
    restart: always
    ports:
      - "5002:3000"
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
    networks:
      - app_network

  frontend:
    build: ./client
    container_name: web_chat_frontend
    restart: always
    ports:
      - "5001:5173"
    env_file:
      - ./client/.env
    depends_on:
      - backend
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

volumes:
  postgres-data:

networks:
  postgres-network:
  redis-network:
  app_network: